# Generated by Django 4.2.6 on 2023-10-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla_estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('cidade', models.ForeignKey(default='não definido', on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
                ('curso', models.ForeignKey(default='não definido', on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
